"""initial PostgreSQL schema

Revision ID: v295_initial_schema
Revises: 
Create Date: 2026-07-14 17:55:06.695805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'v295_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_roles',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('permissions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_roles_code'), 'admin_roles', ['code'], unique=True)
    op.create_index(op.f('ix_admin_roles_id'), 'admin_roles', ['id'], unique=False)
    op.create_table('bosses',
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('boss_type', sa.String(length=30), nullable=False),
    sa.Column('hp', sa.Numeric(precision=40, scale=0), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('summon_rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bosses_code'), 'bosses', ['code'], unique=True)
    op.create_index(op.f('ix_bosses_id'), 'bosses', ['id'], unique=False)
    op.create_table('characters',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_code'), 'characters', ['code'], unique=True)
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_table('drop_tables',
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('owner_type', sa.String(length=40), nullable=False),
    sa.Column('owner_code', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drop_tables_code'), 'drop_tables', ['code'], unique=True)
    op.create_index(op.f('ix_drop_tables_id'), 'drop_tables', ['id'], unique=False)
    op.create_index(op.f('ix_drop_tables_owner_code'), 'drop_tables', ['owner_code'], unique=False)
    op.create_table('enhancement_groups',
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_level', sa.Integer(), nullable=False),
    sa.Column('rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enhancement_groups_code'), 'enhancement_groups', ['code'], unique=True)
    op.create_index(op.f('ix_enhancement_groups_id'), 'enhancement_groups', ['id'], unique=False)
    op.create_table('field_zones',
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('enemy_hp', sa.Numeric(precision=40, scale=0), nullable=False),
    sa.Column('gold_reward', sa.Numeric(precision=40, scale=0), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entry_rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('farm_rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_zones_code'), 'field_zones', ['code'], unique=True)
    op.create_index(op.f('ix_field_zones_id'), 'field_zones', ['id'], unique=False)
    op.create_table('item_templates',
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('item_type', sa.String(length=60), nullable=False),
    sa.Column('grade', sa.String(length=60), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stackable', sa.Boolean(), nullable=False),
    sa.Column('equip_slot', sa.String(length=60), nullable=True),
    sa.Column('enhance_group_code', sa.String(length=120), nullable=True),
    sa.Column('base_stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('options_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_templates_code'), 'item_templates', ['code'], unique=True)
    op.create_index(op.f('ix_item_templates_id'), 'item_templates', ['id'], unique=False)
    op.create_index(op.f('ix_item_templates_item_type'), 'item_templates', ['item_type'], unique=False)
    op.create_table('skills',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slot_key', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('proc_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('options_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_code'), 'skills', ['code'], unique=True)
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('admin_change_logs',
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rollback_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_change_logs_admin_user_id'), 'admin_change_logs', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_change_logs_id'), 'admin_change_logs', ['id'], unique=False)
    op.create_index(op.f('ix_admin_change_logs_target_id'), 'admin_change_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_admin_change_logs_target_type'), 'admin_change_logs', ['target_type'], unique=False)
    op.create_table('admin_user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_code', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_code'], ['admin_roles.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_roles_id'), 'admin_user_roles', ['id'], unique=False)
    op.create_index(op.f('ix_admin_user_roles_user_id'), 'admin_user_roles', ['user_id'], unique=False)
    op.create_table('character_skills',
    sa.Column('character_code', sa.String(length=80), nullable=False),
    sa.Column('skill_code', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_code'], ['characters.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_code'], ['skills.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_code', 'skill_code', name='uq_character_skill')
    )
    op.create_index(op.f('ix_character_skills_id'), 'character_skills', ['id'], unique=False)
    op.create_table('drop_table_items',
    sa.Column('drop_table_code', sa.String(length=120), nullable=False),
    sa.Column('item_template_code', sa.String(length=120), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('max_quantity', sa.Integer(), nullable=False),
    sa.Column('conditions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drop_table_code'], ['drop_tables.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_template_code'], ['item_templates.code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drop_table_items_id'), 'drop_table_items', ['id'], unique=False)
    op.create_table('enhancement_levels',
    sa.Column('group_code', sa.String(length=120), nullable=False),
    sa.Column('from_level', sa.Integer(), nullable=False),
    sa.Column('to_level', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('gold_cost', sa.Numeric(precision=40, scale=0), nullable=False),
    sa.Column('material_rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fail_rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_code'], ['enhancement_groups.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_code', 'from_level', name='uq_enhancement_step')
    )
    op.create_index(op.f('ix_enhancement_levels_id'), 'enhancement_levels', ['id'], unique=False)
    op.create_table('item_instances',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_code', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('enhance_level', sa.Integer(), nullable=False),
    sa.Column('bound_character_code', sa.String(length=80), nullable=True),
    sa.Column('instance_stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('instance_options_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_code'], ['item_templates.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_instances_id'), 'item_instances', ['id'], unique=False)
    op.create_index(op.f('ix_item_instances_user_id'), 'item_instances', ['user_id'], unique=False)
    op.create_table('skill_levels',
    sa.Column('skill_code', sa.String(length=80), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('damage_multiplier', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('proc_rate_bonus', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('options_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_code'], ['skills.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_code', 'level', name='uq_skill_level')
    )
    op.create_index(op.f('ix_skill_levels_id'), 'skill_levels', ['id'], unique=False)
    op.create_table('user_character_skills',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_code', sa.String(length=80), nullable=False),
    sa.Column('skill_code', sa.String(length=80), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_awakened', sa.Boolean(), nullable=False),
    sa.Column('state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_code'], ['characters.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_code'], ['skills.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'character_code', 'skill_code', name='uq_user_character_skill')
    )
    op.create_index(op.f('ix_user_character_skills_id'), 'user_character_skills', ['id'], unique=False)
    op.create_table('user_mailbox_messages',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('rewards_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('claimed', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_mailbox_messages_id'), 'user_mailbox_messages', ['id'], unique=False)
    op.create_index(op.f('ix_user_mailbox_messages_user_id'), 'user_mailbox_messages', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Numeric(precision=40, scale=0), nullable=False),
    sa.Column('farm_atk_bonus', sa.Float(), nullable=False),
    sa.Column('add_attack_speed', sa.Float(), nullable=False),
    sa.Column('current_character_id', sa.String(length=80), nullable=False),
    sa.Column('current_zone_index', sa.Integer(), nullable=False),
    sa.Column('current_zone_type', sa.String(length=30), nullable=False),
    sa.Column('flags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('records_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('user_save_snapshots',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot_key', sa.String(length=80), nullable=False),
    sa.Column('client_save_key', sa.String(length=120), nullable=False),
    sa.Column('save_version', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slot_key', name='uq_user_save_snapshot_slot')
    )
    op.create_index(op.f('ix_user_save_snapshots_id'), 'user_save_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_user_save_snapshots_user_id'), 'user_save_snapshots', ['user_id'], unique=False)
    op.create_table('user_equipment_slots',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_code', sa.String(length=80), nullable=False),
    sa.Column('slot_key', sa.String(length=60), nullable=False),
    sa.Column('item_instance_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_instance_id'], ['item_instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_equipment_slots_id'), 'user_equipment_slots', ['id'], unique=False)
    op.create_index(op.f('ix_user_equipment_slots_user_id'), 'user_equipment_slots', ['user_id'], unique=False)
    op.create_table('user_inventory_slots',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bag_type', sa.String(length=30), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('item_instance_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_instance_id'], ['item_instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_inventory_slots_id'), 'user_inventory_slots', ['id'], unique=False)
    op.create_index(op.f('ix_user_inventory_slots_user_id'), 'user_inventory_slots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_inventory_slots_user_id'), table_name='user_inventory_slots')
    op.drop_index(op.f('ix_user_inventory_slots_id'), table_name='user_inventory_slots')
    op.drop_table('user_inventory_slots')
    op.drop_index(op.f('ix_user_equipment_slots_user_id'), table_name='user_equipment_slots')
    op.drop_index(op.f('ix_user_equipment_slots_id'), table_name='user_equipment_slots')
    op.drop_table('user_equipment_slots')
    op.drop_index(op.f('ix_user_save_snapshots_user_id'), table_name='user_save_snapshots')
    op.drop_index(op.f('ix_user_save_snapshots_id'), table_name='user_save_snapshots')
    op.drop_table('user_save_snapshots')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_mailbox_messages_user_id'), table_name='user_mailbox_messages')
    op.drop_index(op.f('ix_user_mailbox_messages_id'), table_name='user_mailbox_messages')
    op.drop_table('user_mailbox_messages')
    op.drop_index(op.f('ix_user_character_skills_id'), table_name='user_character_skills')
    op.drop_table('user_character_skills')
    op.drop_index(op.f('ix_skill_levels_id'), table_name='skill_levels')
    op.drop_table('skill_levels')
    op.drop_index(op.f('ix_item_instances_user_id'), table_name='item_instances')
    op.drop_index(op.f('ix_item_instances_id'), table_name='item_instances')
    op.drop_table('item_instances')
    op.drop_index(op.f('ix_enhancement_levels_id'), table_name='enhancement_levels')
    op.drop_table('enhancement_levels')
    op.drop_index(op.f('ix_drop_table_items_id'), table_name='drop_table_items')
    op.drop_table('drop_table_items')
    op.drop_index(op.f('ix_character_skills_id'), table_name='character_skills')
    op.drop_table('character_skills')
    op.drop_index(op.f('ix_admin_user_roles_user_id'), table_name='admin_user_roles')
    op.drop_index(op.f('ix_admin_user_roles_id'), table_name='admin_user_roles')
    op.drop_table('admin_user_roles')
    op.drop_index(op.f('ix_admin_change_logs_target_type'), table_name='admin_change_logs')
    op.drop_index(op.f('ix_admin_change_logs_target_id'), table_name='admin_change_logs')
    op.drop_index(op.f('ix_admin_change_logs_id'), table_name='admin_change_logs')
    op.drop_index(op.f('ix_admin_change_logs_admin_user_id'), table_name='admin_change_logs')
    op.drop_table('admin_change_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_code'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_item_templates_item_type'), table_name='item_templates')
    op.drop_index(op.f('ix_item_templates_id'), table_name='item_templates')
    op.drop_index(op.f('ix_item_templates_code'), table_name='item_templates')
    op.drop_table('item_templates')
    op.drop_index(op.f('ix_field_zones_id'), table_name='field_zones')
    op.drop_index(op.f('ix_field_zones_code'), table_name='field_zones')
    op.drop_table('field_zones')
    op.drop_index(op.f('ix_enhancement_groups_id'), table_name='enhancement_groups')
    op.drop_index(op.f('ix_enhancement_groups_code'), table_name='enhancement_groups')
    op.drop_table('enhancement_groups')
    op.drop_index(op.f('ix_drop_tables_owner_code'), table_name='drop_tables')
    op.drop_index(op.f('ix_drop_tables_id'), table_name='drop_tables')
    op.drop_index(op.f('ix_drop_tables_code'), table_name='drop_tables')
    op.drop_table('drop_tables')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_code'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_bosses_id'), table_name='bosses')
    op.drop_index(op.f('ix_bosses_code'), table_name='bosses')
    op.drop_table('bosses')
    op.drop_index(op.f('ix_admin_roles_id'), table_name='admin_roles')
    op.drop_index(op.f('ix_admin_roles_code'), table_name='admin_roles')
    op.drop_table('admin_roles')
    # ### end Alembic commands ###
